## Numpy exercises and tests.
It's just a notebook that i used to learn and test a lot of things using the numpy package. Really simple things. As it's something really really simple and it's just a notebook that i use sometimes when I forgot something i will mantain in portuguese.

In [135]:
import sys
import numpy as np

In [136]:
# criando array
np.array([1, 2, 3, 4])

array([1, 2, 3, 4])

In [137]:
# criando array com float. Se tem um float logo o array irá transformar todos elementos em floats
np.array([0, 2., 3, 4])

array([0., 2., 3., 4.])

In [138]:
# para saber o tipo da array precisamos escrever *x.dtype*
b = np.array([0, .5, -1, 1.5, 2])
b.dtype

dtype('float64')

In [139]:
#para criar um array de um tipo especifico usamos o seguinte comando:

np.array([2,3,4], dtype=np.float64)

array([2., 3., 4.])

In [140]:
np.array([1, 3, 4, 5, 1], dtype=np.int8)

array([1, 3, 4, 5, 1], dtype=int8)

In [141]:
c = np.array(['asdqf',1. ,0. , '123f','321', True])
c.dtype

dtype('<U32')

In [142]:
# pra descobrir as dimensões de uma array usamos o comando shape
a = np.array([[0,2,3,4,1],[2,3,4,5,1]])
a.shape

(2, 5)

In [143]:
#descobrir o numero de elementos usamos size
a.size

10

In [144]:
#quantas dimensões uasmos ndim
b = np.array([[[0,1],[0,2]],[[0,2],[1,3]]])
a.ndim

2

In [145]:
b[0][0][1]

1

In [146]:
b[0, 0, 1]

1

In [147]:
# mesmo comportamento com arrays.
k = [[0,2],[0,3], [0,65]]
k[::-1]


[[0, 65], [0, 3], [0, 2]]

In [148]:
m = np.array([[0,2, 4],[0,3, 1], [0,65, 23]])
print(m.ndim, m.shape)
m[:1:-1]

2 (3, 3)


array([[ 0, 65, 23]])

In [149]:
# aqui vemos que ao colocar a virgula decidimos quais elementos
# vamos pegar da segunda dimensão e como. Por exemplo aqui pegamos
# os elementos de tras pra frente.

m[1:, ::-1]

array([[ 1,  3,  0],
       [23, 65,  0]])

In [150]:
# o mesmo ocorre com arrays
qw = [
    [1,2],
    [3,4]
]
qw[0] = [0,0]
print(qw)

[[0, 0], [3, 4]]


In [151]:
ar = np.array([
    [1,3,4],
    [3,1,4]
])
ar

array([[1, 3, 4],
       [3, 1, 4]])

In [152]:
ar[0] = [0,80,0]
ar

array([[ 0, 80,  0],
       [ 3,  1,  4]])

In [153]:
# caso queira mudar todos elementos de uma linha faço assim:
ar[1] = 2
ar

array([[ 0, 80,  0],
       [ 2,  2,  2]])

In [154]:
#a soma de uma array é q nem a somatoria de uma lista
ar.sum()

86

In [155]:
# desvio padrão de uma array
ar.std()

29.380643665893746

In [156]:
# da a variação sla pra q uso isso
ac = np.array([1, 2])
ac.var()

0.25

In [157]:
ar.mean() # media

14.333333333333334

In [158]:
# podemos somar os eixos de uma matriz tambem
# podemos fazer isso com as outras operações também.
p = np.array([
    [[1,2,3],
    [3,4,5]],
    [[1,2,3],
    [3,4,5]]
])
print(p.shape, p.ndim)
p.sum(axis=0)

(2, 2, 3) 3


array([[ 2,  4,  6],
       [ 6,  8, 10]])

In [159]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [160]:
a + 10

array([10, 11, 12, 13, 14])

In [161]:
a * 2

array([0, 2, 4, 6, 8])

In [162]:
a += 2

In [163]:
a

array([2, 3, 4, 5, 6])

In [164]:
b = np.arange(5)

In [165]:
b

array([0, 1, 2, 3, 4])

In [166]:
b + a

array([ 2,  4,  6,  8, 10])

In [167]:
b * a

array([ 0,  3,  8, 15, 24])

In [168]:
b = b + a/2

In [169]:
b

array([1. , 2.5, 4. , 5.5, 7. ])

In [170]:
b[b >= 1]

array([1. , 2.5, 4. , 5.5, 7. ])

In [171]:
b[b >= b.mean()]

array([4. , 5.5, 7. ])

In [172]:
b[~(b >= b.mean())]

array([1. , 2.5])

In [173]:
b[(b > 4) | (b == 2.5)]

array([2.5, 5.5, 7. ])

In [174]:
Ronaldo = np.array(np.random.randint(100, size=(2,2,1 )), dtype=np.float64)

In [175]:
Ronaldo

array([[[23.],
        [32.]],

       [[51.],
        [ 6.]]])

In [176]:
np.random.randint(100, size=(2))

array([ 0, 29])

In [177]:
# multiplicação de matrizes usamos o comando dot ou @
a = np.random.randint(10, size = (2,2))
b = np.random.randint(10, size = (2,2))

In [178]:
a

array([[8, 1],
       [9, 0]])

In [179]:
b

array([[2, 0],
       [8, 8]])

In [180]:
a.dot(b)

array([[24,  8],
       [18,  0]])

In [181]:
b.dot(a)

array([[ 16,   2],
       [136,   8]])

In [182]:
# pra pegar a matriz transposta usamos T:
a.T

array([[8, 9],
       [1, 0]])

In [183]:
b.T

array([[2, 8],
       [0, 8]])

In [207]:
#tamanho de um objeto na memoria do computador:
sys.getsizeof(2000000000)

32

In [206]:
sys.getsizeof(np.int8(2000000000))

25

In [208]:
np.dtype(np.int8).itemsize

1

In [212]:
np.dtype(float).itemsize

8

In [216]:
np.dtype(np.float16).itemsize

2

In [230]:
%time sum((list(range(200000))))

Wall time: 18 ms


19999900000

In [224]:
%time (np.arange(200000).sum())

Wall time: 998 µs


-1474936480

In [231]:
np.arange(22).sum()

231

In [232]:
print(sum(list(range(22))))

231


In [238]:
np.random.randint(20, size=2)

array([13, 18])

In [257]:
np.random.normal(size=5)

array([ 1.94290678,  1.82399794,  1.91931706, -0.78021755,  1.24436195])

In [262]:
np.random.rand(2,3)

array([[0.03237967, 0.73323787, 0.96530672],
       [0.93564482, 0.91232297, 0.14344185]])

In [263]:
np.arange(10).reshape(2, 5)


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [268]:
np.linspace(1, 3, 5)
# interessante

array([1. , 1.5, 2. , 2.5, 3. ])

In [276]:
np.empty(5)

array([1. , 1.5, 2. , 2.5, 3. ])

In [277]:
np.empty((2, 2))

array([[0.        , 0.33333333],
       [0.66666667, 1.        ]])

In [278]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [282]:
np.eye(4, 2)

array([[1., 0.],
       [0., 1.],
       [0., 0.],
       [0., 0.]])

In [284]:
"Hello World"[6]

'W'